### ISSUE TITLE
Blog vs README discrepancy

### ISSUE THREAD

**Issue by kastiglione** [revealapp/ConstraintsFightTransforms#1]
Regarding which AL behavior is used, the README here states:

> when linking against iOS 7 SDK **or** running on an iOS 7 device. When linking against iOS 8 SDK **and** running on an iOS 8 device

The blog states:

> The function itself returns `YES` if the app is linked against iOS 8 SDK, and `NO` otherwise

Unless I'm misunderstanding, I think the blog needs to be updated to mention the iOS 7 check in the logic.

Thanks for the article!

**Comment by vlas-voloshin** [comment]
@kastiglione thanks for your feedback! The quote from the blog you mentioned refers to a private function in iOS 8 runtime UIKit framework, and it's not present in iOS 7 at all. On the latter, the legacy behaviour is actually the _only_ behaviour. The function makes sure that if an app was linked against _iOS 7 SDK_ it gets behaviour of _iOS 7_ even though it's running on _iOS 8_.
Hopefully this clarifies it a bit!

**Comment by kastiglione** [comment]
I see, thanks!
